name: Web Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.45
        
    - name: Create Build Directory
      run: mkdir -p build_web
      
    - name: Configure CMake
      run: |
        cd build_web
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: |
        cd build_web
        emmake make
        
    - name: Create Web Directory
      run: mkdir -p web_output
      
    - name: Copy Build Artifacts
      run: |
        cp build_web/*.js web_output/ || true
        cp build_web/*.wasm web_output/ || true
        cp build_web/*.html web_output/ || true
        cp build_web/*.data web_output/ || true
        # Create a simple index.html if it doesn't exist
        if [ ! -f web_output/index.html ]; then
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>C++ Roguelike</title></head><body><script src='$(ls web_output/*.js | head -1 | xargs basename)'></script></body></html>" > web_output/index.html
        fi
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web_output/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web_output
        branch: gh-pages