name: Web Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 'latest'
        actions-cache-folder: 'emsdk-cache'
    
    - name: Verify Emscripten installation
      run: emcc --version
    
    - name: Create build directory
      run: mkdir -p build_web
    
    - name: Configure CMake
      working-directory: ./build_web
      run: |
        emcmake cmake .. -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DEMSCRIPTEN=ON \
          -DCMAKE_EXE_LINKER_FLAGS="-s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='[\"png\"]' -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s EXPORTED_RUNTIME_METHODS='[\"ccall\",\"cwrap\"]' --preload-file ../assets@/assets"
    
    - name: Build
      working-directory: ./build_web
      run: cmake --build .
    
    - name: Create web distribution directory
      run: mkdir -p web_dist
    
    - name: Copy build artifacts to distribution directory
      run: |
        cp build_web/*.html web_dist/
        cp build_web/*.js web_dist/
        cp build_web/*.wasm web_dist/
        cp build_web/*.data web_dist/ || true
    
    - name: Create simple index page
      run: |
        if [ ! -f build_web/index.html ]; then
          cat > web_dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>C++ Roguelike</title>
            <style>
              body {
                margin: 0;
                background-color: #222;
                color: #eee;
                font-family: sans-serif;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                min-height: 100vh;
              }
              canvas {
                border: 1px solid #444;
                display: block;
                margin: 0 auto;
              }
              h1 {
                text-align: center;
                margin-bottom: 20px;
              }
              #loading {
                text-align: center;
                margin-top: 20px;
              }
            </style>
          </head>
          <body>
            <h1>C++ Roguelike</h1>
            <div id="canvas-container"></div>
            <div id="loading">Loading...</div>
            <script>
              // Redirect to the appropriate HTML file that was generated by Emscripten
              window.onload = function() {
                // Change this to the actual name of your executable
                window.location.href = "CppRogueLike.html";
              }
            </script>
          </body>
          </html>
          EOL
        else
          cp build_web/index.html web_dist/
        fi
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web_dist
        branch: gh-pages
        clean: true