name: Web Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      
    - name: Verify Emscripten
      run: emcc --version
      
    - name: Create Build Directory
      run: mkdir -p build_web
      
    - name: Configure CMake
      run: |
        cd build_web
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: |
        cd build_web
        emmake make
        
    - name: List build files
      run: find build_web -type f -name "*.js" -o -name "*.wasm" -o -name "*.html"
      
    - name: Create output directory
      run: mkdir -p web_build
      
    - name: Copy build files
      run: |
        cp build_web/*.js web_build/ || echo "No JS files found"
        cp build_web/*.wasm web_build/ || echo "No WASM files found"
        cp build_web/*.html web_build/ || echo "No HTML files found"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web_build/