name: Web Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 'latest'
        no-cache: true
    
    - name: Create build directory
      run: mkdir -p build_web
    
    - name: Configure CMake
      working-directory: ./build_web
      run: |
        emcmake cmake .. -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -w" \
          -DCMAKE_EXE_LINKER_FLAGS="-s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1"
    
    - name: Build
      working-directory: ./build_web
      run: cmake --build .
    
    - name: Create web distribution directory
      run: mkdir -p web_dist
    
    - name: Copy build artifacts
      run: |
        cp build_web/*.html web_dist/ || true
        cp build_web/*.js web_dist/ || true
        cp build_web/*.wasm web_dist/ || true
        cp build_web/*.data web_dist/ || true
    
    - name: Create index.html if needed
      run: |
        if [ -f "web_dist/shell.html" ] && [ ! -f "web_dist/index.html" ]; then
          cp web_dist/shell.html web_dist/index.html
        fi
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web_dist
        branch: gh-pages
        clean: true